name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-ax650:
    name: AX650 Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare 3rdparty
        run: git submodule update --init

      - name: Build AX650
        run: bash ./build_ax650.sh

      - name: Upload AX650 artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-ax650
          path: build_650/install/

  build-axcl-x86:
    name: AXCL x86 Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare 3rdparty
        run: git submodule update --init

      - name: Build AXCL x86
        run: bash ./build_axcl_x86.sh

      - name: Upload AXCL x86 artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-axcl-x86
          path: build_axcl_x86/install/

  build-axcl-aarch64:
    name: AXCL aarch64 Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare 3rdparty
        run: git submodule update --init

      - name: Build AXCL aarch64
        run: bash ./build_axcl_aarch64.sh

      - name: Upload AXCL aarch64 artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-axcl-aarch64
          path: build_axcl_aarch64/install/
